// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYpcnBGDKurMhXHeNxMxjCs3hxRS_wvmk',
    appId: '1:1029833096928:web:afe48896426f7f56795a85',
    messagingSenderId: '1029833096928',
    projectId: 'decorar-project',
    authDomain: 'decorar-project.firebaseapp.com',
    storageBucket: 'decorar-project.firebasestorage.app',
    measurementId: 'G-VX2RQWYJEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTLa83StfoabICWDaQ1BrTRgcHPpI6XjI',
    appId: '1:1029833096928:android:6e17eab1c18c6dd5795a85',
    messagingSenderId: '1029833096928',
    projectId: 'decorar-project',
    storageBucket: 'decorar-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmmOa-QJmJuV-rGUZCdoeQjXRKfnX6bYE',
    appId: '1:1029833096928:ios:cd61e5fbc78e0dab795a85',
    messagingSenderId: '1029833096928',
    projectId: 'decorar-project',
    storageBucket: 'decorar-project.firebasestorage.app',
    iosBundleId: 'com.example.interiorDesignAr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmmOa-QJmJuV-rGUZCdoeQjXRKfnX6bYE',
    appId: '1:1029833096928:ios:cd61e5fbc78e0dab795a85',
    messagingSenderId: '1029833096928',
    projectId: 'decorar-project',
    storageBucket: 'decorar-project.firebasestorage.app',
    iosBundleId: 'com.example.interiorDesignAr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYpcnBGDKurMhXHeNxMxjCs3hxRS_wvmk',
    appId: '1:1029833096928:web:acd33e58e3022b4a795a85',
    messagingSenderId: '1029833096928',
    projectId: 'decorar-project',
    authDomain: 'decorar-project.firebaseapp.com',
    storageBucket: 'decorar-project.firebasestorage.app',
    measurementId: 'G-GDLQ6L301F',
  );

}